runtime: nodejs18

service: frontend

handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
  http_headers:
    Cache-Control: "max-age=86400, must-revalidate" # 24 hours
# Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html
  http_headers:
        Cache-Control: "no-cache, must-revalidate" # No cache for HTML file