version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload --workers 4
    volumes:
      - .:/usr/src/app
      - shared_data:/usr/src/app/shared  # Mount the shared volume
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - worker

  worker:
    build: .
    command: rq worker --url redis://redis:6379
    volumes:
      - .:/usr/src/app
      - shared_data:/usr/src/app/shared  # Mount the shared volume
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    expose:
      - "6379"

volumes:
  shared_data: 